[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_nft_project = "EqvXgPF29CWxTp7a7ZFrvtM87cs3e24EwpFPCiw6bEAU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
